// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/google/albums.ts";
import * as $2 from "./routes/api/google/upload.ts";
import * as $3 from "./routes/api/twitter.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/redirect.tsx";
import * as $6 from "./routes/twitter2gphoto.tsx";
import * as $$0 from "./islands/SavePhoto.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/google/albums.ts": $1,
    "./routes/api/google/upload.ts": $2,
    "./routes/api/twitter.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/redirect.tsx": $5,
    "./routes/twitter2gphoto.tsx": $6,
  },
  islands: {
    "./islands/SavePhoto.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
